# Generated by Django 5.1.4 on 2024-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_father', models.CharField(max_length=20)),
                ('joindate', models.DateField(max_length=20)),
                ('stu_class', models.CharField(max_length=20)),
                ('fees', models.PositiveIntegerField(max_length=20)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
            },
        ),
    ]
